// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follow.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH
  insterted_feed_follow AS (
    INSERT INTO
      feed_follows (id, user_id, feed_id, created_at, updated_at)
    VALUES
      ($1, $2, $3, $4, $5)
    RETURNING
      id, user_id, feed_id, created_at, updated_at
  )
SELECT
  insterted_feed_follow.id, insterted_feed_follow.user_id, insterted_feed_follow.feed_id, insterted_feed_follow.created_at, insterted_feed_follow.updated_at,
  users.id, users.name, users.created_at, users.updated_at,
  feeds.id, feeds.name, feeds.url, feeds.user_id, feeds.created_at, feeds.updated_at
FROM
  insterted_feed_follow
  INNER JOIN users ON users.id = insterted_feed_follow.user_id
  INNER JOIN feeds ON feeds.id = insterted_feed_follow.feed_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	User      User
	Feed      Feed
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.Feed.ID,
		&i.Feed.Name,
		&i.Feed.Url,
		&i.Feed.UserID,
		&i.Feed.CreatedAt,
		&i.Feed.UpdatedAt,
	)
	return i, err
}
