// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mark_feed_fetched.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const markFeedFetched = `-- name: MarkFeedFetched :one
UPDATE feeds
SET
  last_fetched_at = $1,
  updated_at = $2
WHERE
  feeds.id = $3
RETURNING
  id, name, url, user_id, created_at, updated_at, last_fetched_at
`

type MarkFeedFetchedParams struct {
	LastFetchedAt sql.NullTime
	UpdatedAt     time.Time
	ID            uuid.UUID
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetched, arg.LastFetchedAt, arg.UpdatedAt, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFetchedAt,
	)
	return i, err
}
